name: calibre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  sign_in_button: ^3.2.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Bender.otf
        - asset: assets/fonts/Bender Light.otf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf