name: calibre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Bender.otf
        - asset: assets/fonts/Bender Light.otf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf